apiVersion: apps/v1
kind: Deployment
metadata:
  name: micall
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micall
  template:
    metadata:
      labels:
        app: micall
    spec:
      containers:
        - name: micall
          image: micall:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: micall-secrets
                  key: mongodb-uri
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
